"""initial_schema

Revision ID: 83abe7eb52df
Revises: 
Create Date: 2026-03-30 14:32:03.117904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '83abe7eb52df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('s2_id', sa.String(), nullable=True),
    sa.Column('arxiv_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('authors', sqlite.JSON(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('abstract', sa.String(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('reference_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('open_access', sa.Boolean(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arxiv_id'),
    sa.UniqueConstraint('doi'),
    sa.UniqueConstraint('s2_id')
    )
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_index('idx_papers_arxiv', ['arxiv_id'], unique=False, sqlite_where=sa.text('arxiv_id IS NOT NULL'))
        batch_op.create_index('idx_papers_doi', ['doi'], unique=False, sqlite_where=sa.text('doi IS NOT NULL'))
        batch_op.create_index('idx_papers_s2_id', ['s2_id'], unique=False, sqlite_where=sa.text('s2_id IS NOT NULL'))
        batch_op.create_index('idx_papers_title', ['title'], unique=False)
        batch_op.create_index('idx_papers_year', ['year'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('user_query', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('output_types', sqlite.JSON(), nullable=False),
    sa.Column('output_language', sa.String(), nullable=False),
    sa.Column('citation_style', sa.String(), nullable=False),
    sa.Column('search_config', sqlite.JSON(), nullable=True),
    sa.Column('paper_count', sa.Integer(), nullable=False),
    sa.Column('token_usage', sqlite.JSON(), nullable=True),
    sa.Column('token_budget', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('idx_projects_created', ['created_at'], unique=False)
        batch_op.create_index('idx_projects_status', ['status'], unique=False, sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.create_index('idx_projects_user', ['user_id'], unique=False, sqlite_where=sa.text('user_id IS NOT NULL AND deleted_at IS NULL'))

    op.create_table('paper_analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('paper_id', sa.String(), nullable=False),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('methodology', sa.String(), nullable=True),
    sa.Column('datasets', sqlite.JSON(), nullable=True),
    sa.Column('findings', sa.String(), nullable=True),
    sa.Column('limitations', sa.String(), nullable=True),
    sa.Column('method_category', sa.String(), nullable=True),
    sa.Column('method_details', sqlite.JSON(), nullable=True),
    sa.Column('key_concepts', sqlite.JSON(), nullable=True),
    sa.Column('relations', sqlite.JSON(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_notes', sa.String(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('analysis_depth', sa.String(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_analyses', schema=None) as batch_op:
        batch_op.create_index('idx_analysis_paper', ['paper_id'], unique=False, sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.create_index('idx_analysis_project', ['project_id'], unique=False, sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.create_index('idx_analysis_unique_active', ['project_id', 'paper_id'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('paper_fulltext',
    sa.Column('paper_id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('parser_used', sa.String(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('paper_id')
    )
    op.create_table('project_papers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('paper_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('found_by', sa.String(), nullable=True),
    sa.Column('search_query', sa.String(), nullable=True),
    sa.Column('relevance_rank', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_papers', schema=None) as batch_op:
        batch_op.create_index('idx_pp_paper', ['paper_id'], unique=False, sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.create_index('idx_pp_project', ['project_id'], unique=False, sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.create_index('idx_pp_status', ['project_id', 'status'], unique=False, sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.create_index('idx_pp_unique_active', ['project_id', 'paper_id'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('review_outputs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('output_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('outline', sqlite.JSON(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('structured_data', sqlite.JSON(), nullable=True),
    sa.Column('references', sqlite.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('revision_notes', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('citation_style', sa.String(), nullable=False),
    sa.Column('writing_style', sa.String(), nullable=True),
    sa.Column('citation_verification', sqlite.JSON(), nullable=True),
    sa.Column('export_formats', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['review_outputs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_outputs', schema=None) as batch_op:
        batch_op.create_index('idx_outputs_project', ['project_id'], unique=False, sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.create_index('idx_outputs_project_type', ['project_id', 'output_type'], unique=False, sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.create_index('idx_outputs_type', ['output_type'], unique=False, sqlite_where=sa.text('deleted_at IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_outputs', schema=None) as batch_op:
        batch_op.drop_index('idx_outputs_type', sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index('idx_outputs_project_type', sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index('idx_outputs_project', sqlite_where=sa.text('deleted_at IS NULL'))

    op.drop_table('review_outputs')
    with op.batch_alter_table('project_papers', schema=None) as batch_op:
        batch_op.drop_index('idx_pp_unique_active', sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index('idx_pp_status', sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index('idx_pp_project', sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index('idx_pp_paper', sqlite_where=sa.text('deleted_at IS NULL'))

    op.drop_table('project_papers')
    op.drop_table('paper_fulltext')
    with op.batch_alter_table('paper_analyses', schema=None) as batch_op:
        batch_op.drop_index('idx_analysis_unique_active', sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index('idx_analysis_project', sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index('idx_analysis_paper', sqlite_where=sa.text('deleted_at IS NULL'))

    op.drop_table('paper_analyses')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('idx_projects_user', sqlite_where=sa.text('user_id IS NOT NULL AND deleted_at IS NULL'))
        batch_op.drop_index('idx_projects_status', sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index('idx_projects_created')

    op.drop_table('projects')
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index('idx_papers_year')
        batch_op.drop_index('idx_papers_title')
        batch_op.drop_index('idx_papers_s2_id', sqlite_where=sa.text('s2_id IS NOT NULL'))
        batch_op.drop_index('idx_papers_doi', sqlite_where=sa.text('doi IS NOT NULL'))
        batch_op.drop_index('idx_papers_arxiv', sqlite_where=sa.text('arxiv_id IS NOT NULL'))

    op.drop_table('papers')
    # ### end Alembic commands ###
